### ISSUE TITLE
Evaluate other oci library

### ISSUE THREAD

**Issue by schrodit** [gardener/component-cli#10]
**Description**:

currently we use the docker/containerd library that is also used by the major container runtimes and the docker cli.
As this library is mostly build for the docker purpose and it is not as a general oci artifact tool we should evaluate a more lightweight library like https://github.com/google/go-containerregistry .

This lib from google is a lightweight reimplementation and uses raw http calls.
We already use parts of the library for authentication.

**Comment by In-Ko** [comment]
Not relevant currently.
