### ISSUE TITLE
make install on Mac fails

### ISSUE THREAD

**Issue by guewa** [gardener/component-cli#15]
**What happened**:
`make install` on "clean" MacOS brings error
```
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
Please document to install correct date command

**Environment**:

**Comment by schrodit** [comment]
The install script uses the gnu utils for the date generation which is by default not installed on a mac system.
Here is a small script that shows how i can be installed:
```
Please make sure you have installed the following requirements:
- GNU Core Utils
- GNU Tar
- GNU Sed
- GNU Parallel
Brew command:
$ brew install coreutils gnu-sed gnu-tar grep jq parallel
Please allow them to be used without their "g" prefix:
$ export PATH=/usr/local/opt/coreutils/libexec/gnubin:\$PATH
$ export PATH=/usr/local/opt/gnu-sed/libexec/gnubin:\$PATH
$ export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:\$PATH
$ export PATH=/usr/local/opt/grep/libexec/gnubin:\$PATH
```

I will also that as info to the install-requirements script

**Comment by schrodit** [comment]
Added info with https://github.com/gardener/component-cli/commit/f52fdc7c36b07f74a231bcf8867db9ab5e740350
