### ISSUE TITLE
Oci copy changes manifest attribute order

### ISSUE THREAD

**Issue by enrico-kaack-comp** [gardener/component-cli#39]
**What happened**:
Using the oci copy command, the resulting manifest in the target registry may have a different attribute order. This results in a different hash.
**What you expected to happen**:
Using oci copy should result in the exact same manifest and manifest hash.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:
Reason for this bug is probably the deserialisation of the manifest and a later serialisation before uploading the manifest. During the serialisation, the attribute order may change depending on the library used. 

Better behavior would be to skip the serialisation and upload the original manifest.

**Environment**:

**Comment by jschicktanz** [comment]
fixed by #71 . Manifests are now copied 1:1 without deserialization/serialization.
