### ISSUE TITLE
Unnecessary param -a, --archive string in 'component-archive create'

### ISSUE THREAD

**Issue by guewa** [gardener/component-cli#42]
**What would you like to be added**:
The parameter -a, --archive string is not needed as this is the mandatory 1st parameter

**Why is this needed**:
Could lead to irritation, as defined as optional.

Parameter is inherited by the default builder options, maybe it's possible to remove especially for the create command.

**Comment by In-Ko** [comment]
Move to new backlog project with low prio.

**Comment by In-Ko** [comment]
Closing, as it has been moved to new backlog.
