### ISSUE TITLE
Authorisation issue during pushing a blueprint

### ISSUE THREAD

**Issue by robertgraeff** [gardener/component-cli#6]
**What happened**:
I am trying to push a component descriptor (resp. blueprint) to an OCI registry using the component CLI command `landscaper-cli components-cli component-archive remote push`. I have performed the command `gcloud auth configure-docker`, so that my docker config.json contains a gcloud credential helper. But there is also an entry in the `auths` section which already existed before:
```
{
  "auths": {
    "eu.gcr.io": {},
    ...
  },
  "credHelpers": {
    "eu.gcr.io": "gcloud",
    ...
  },
  ...
}
```

The issue is that the gcloud credential helper is not used for authentication as long as there is the entry in the `auths` section. 

In my case, the push failed (Unauthorized) when the `auths`entry was there. After I had removed the entry from the `auths`section the gcloud credential helper was used, and the push succeeded.

**What you expected to happen**:
The credential helper should have been used, regardless of the `auths`entry.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
The version of the component-cli is v0.16.0

**Comment by jschicktanz** [comment]
the reason for the behaviour was probably an expired token that was once used for manually authenticating to GCR (before configuring the credential helper).

as a fix, run `docker logout eu.gcr.io` to remove the expired token and only use the credential helper from this point on.

the actual behaviour of the component-cli when preferring "auths" over "credHelpers" is correct. see also the discussion in #24
