### ISSUE TITLE
component archive create command has inconsistent behavior

### ISSUE THREAD

**Issue by jkafka23** [gardener/component-cli#61]
**What happened**:
Creating a new component descriptor in the same directory in which already an empty component descriptor lives, results in message "Successfully created component archive at", although nothing really happened.  

**What you expected to happen**:
I would have expected to get a message, warning "attention, you are overwriting an existing component descriptor"

**How to reproduce it (as minimally and precisely as possible)**:

Create an new directory, e.g. /test/. CD into /test/ and execute the following command:
component-cli ca create .

then execute this command:
landscaper-cli component-cli component-archive create . --component-name jason_one --component-version v0.1.0

Not sure if this is a bug. If there is a logic behind it, it is at least a little bit obscure. By running this command "component-cli ca create ." one creates an unnamed and versionless CD. Calling the component-CLI again, this time with name and version does not lead to overwriting the previous CD and the tool is totally quiet about it.

**Comment by In-Ko** [comment]
To be moved to new backlog project

**Comment by In-Ko** [comment]
Closed, as moved to other backlog.
