### ISSUE TITLE
Cannot upload blob files in GitHub workflow due to ":" Colon

### ISSUE THREAD

**Issue by DenisDuev** [gardener/component-cli#8]
**What is the problem:**

We are using landscapercli in a GitHub workflow to generate component-descriptor, blueprint, and deployitems based on helm charts.
The helm charts are local and blobs are generated.
When we try to upload the artifacts using [actions/upload-artifacts](https://github.com/actions/upload-artifact) we get an error:
```
Error: Artifact path is not valid: /blobs/sha256:2bd6ba29e8317150032676053759ed56cb26a56db023f2531f7be9a4b7920109. Contains character: ":". Invalid characters include: ",:,<,>,|,*,?.
```

**What you expected to happen**:

Successfully uploaded artifacts in GitHub workflow. File names do not contain characters that do not work on most operating systems. See more [here](https://github.com/actions/toolkit/blob/fc005283374f1cea5e03ea1caf959cd9ff12fdc2/packages/artifact/src/internal/utils.ts#L247)

**How to reproduce it (as minimally and precisely as possible)**:

Greate repository containing a file with ":" in its name, use the https://github.com/actions/upload-artifact to upload it to workflow

Initially, I have opened the issues in [landscaper-cli](https://github.com/gardener/landscapercli/issues/67), but they only wrap the functionality of component-cli

**Comment by In-Ko** [comment]
Closed, as the other issue is also closed.
