### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by schrodit** [gardener/component-cli#9]
**Description**

Currently most code is only tested with unit tests.
But for better test coverage it is necessary to test the component-cli and its workflows with a real registry.

Therefore the following tasks need to be performed:
- [x] create integration test framework for oci registries
  - this can be done similar to the controller-runtime envtest framework that spawn a controlplane using the kubernetes binary
  - The default lightweight registry/registry from docker should be used
  - allow to run multiple instances to also test copy
  - then the testflow would look like:
    - download registry binary
    - run registry
    - perform tests
    - shutdown binary
- [x] Create integration tests for the oci client
- [x] create integration tests for the component descriptor artifacts
- [x] create integration tests for the cli

**Comment by guewa** [comment]
# Integration tests

## component-cli/docs/reference at main · gardener/component-cli · GitHub

## [component-cli.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli.md "component-cli.md")
### [component-cli\_component-archive.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive.md "component-cli_component-archive.md")
#### [component-cli\_component-archive\_component-references.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_component-references.md "component-cli_component-archive_component-references.md")
- [ ] [component-cli\_component-archive\_component-references\_add.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_component-references_add.md "component-cli_component-archive_component-references_add.md") Unittest pkg/commands/componentarchive/componentreferences/add_test.go
- [ ] [component-cli\_component-archive\_create.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_create.md "component-cli_component-archive_create.md")
- [ ] [component-cli\_component-archive\_export.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_export.md "component-cli_component-archive_export.md")
#### [component-cli\_component-archive\_remote.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_remote.md "component-cli_component-archive_remote.md")
- [ ] [component-cli\_component-archive\_remote\_copy.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_remote_copy.md "component-cli_component-archive_remote_copy.md")
- [ ] [component-cli\_component-archive\_remote\_get.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_remote_get.md "component-cli_component-archive_remote_get.md") Integration Test pkg/commands/componentarchive/remote/remote_test.go
- [ ] [component-cli\_component-archive\_remote\_push.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_remote_push.md "component-cli_component-archive_remote_push.md") Integration Test pkg/commands/componentarchive/remote/remote_test.go
#### [component-cli\_component-archive\_resources.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_resources.md "component-cli_component-archive_resources.md")
- [ ] [component-cli\_component-archive\_resources\_add.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_resources_add.md "component-cli_component-archive_resources_add.md") Unit test pkg/commands/componentarchive/resources/add_test.go
#### [component-cli\_component-archive\_sources.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_sources.md "component-cli_component-archive_sources.md")
- [ ] [component-cli\_component-archive\_sources\_add.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_component-archive_sources_add.md "component-cli_component-archive_sources_add.md") Unit test pkg/commands/componentarchive/sources/add_test.go
#### [component-cli\_ctf.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_ctf.md "component-cli_ctf.md")
- [ ] [component-cli\_ctf\_add.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_ctf_add.md "component-cli_ctf_add.md")
- [ ] [component-cli\_ctf\_push.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_ctf_push.md "component-cli_ctf_push.md")
- [ ] [component-cli\_image-vector.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_image-vector.md "component-cli_image-vector.md")
- [ ] [component-cli\_image-vector\_add.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_image-vector_add.md "component-cli_image-vector_add.md")
- [ ] [component-cli\_image-vector\_generate-overwrite.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_image-vector_generate-overwrite.md "component-cli_image-vector_generate-overwrite.md")
- [ ] [component-cli\_oci.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_oci.md "component-cli_oci.md")
- [ ] [component-cli\_oci\_copy.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_oci_copy.md "component-cli_oci_copy.md")
- [ ] [component-cli\_oci\_pull.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_oci_pull.md "component-cli_oci_pull.md")
- [ ] [component-cli\_oci\_repositories.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_oci_repositories.md "component-cli_oci_repositories.md")
- [ ] [component-cli\_oci\_tags.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_oci_tags.md "component-cli_oci_tags.md")
- [ ] [component-cli\_version.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_version.md "component-cli_version.md")

**Comment by guewa** [comment]
## [component-cli_cache.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_cache.md "component-cli_cache.md")

- [x] [component-cli_cache_info.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_cache_info.md) Integration Test /ociclient/cache/cache_suite_test.go

- [x] [component-cli_cache_prune.md](https://github.com/gardener/component-cli/blob/main/docs/reference/component-cli_cache_prune.md Integration Test /ociclient/cache/cache_suite_test.go

**Comment by In-Ko** [comment]
Just found this one while cleaning up. I believe it can this issue can be closed, as it has been moved to closed already months ago on the project board ?
